-- Bu dosya geriye dönük yönlendirmedir. Üretim şeması sürümlü migration'dadır:
-- supabase/migrations/202609010001_fincoach_production_foundation.sql
-- Güvenli uygulama: node --env-file=server/.env scripts/migrate-database.mjs
